Add docs for regulatory-data-deletion api
AdaSupport/documentation pull request #39
Opened 2021-11-30 20:57 UTC by ChrisBehanAda

2022-01-14 22:49 UTC, ashansk approved these changes
This looks good! Covers everything clients would need. Great job! 💯

2022-01-24 16:05 UTC, mdfrncs requested changes

2022-01-24 16:12 UTC, ChrisBehanAda commented on source/includes/data_compliance_api.md.erb
> +|502 - Bad Gateway|Nginx gateway issue on Ada's servers|
Followed the same descriptions used by the Data Export API. I will add a sentence to the 401 to "Try generating a new token"

2022-01-24 21:18 UTC, mdfrncs approved these changes

2022-01-25 21:17 UTC, merged